import { eq, and, inArray, desc, sql, ne, isNotNull } from 'drizzle-orm';
import { z } from 'zod';
import { schema } from '@/db/client';
import type { Ctx } from '@/core/context';
import { ForbiddenError, NotFoundError, ValidationError } from '@/core/errors';
import { getTicket } from '@/modules/tickets/service';
import { similarTickets } from '@/modules/tickets/list';
import { timeline } from '@/modules/tickets/activity';
import { getMajor } from '@/modules/tickets/major';
import { loadTicket, optionsOfType, optionById, isCustomerUser, type TicketRow, type OptionRow } from '@/modules/tickets/common';
import { evaluateAssignment } from '@/modules/tickets/assignment';
import { suggest as kbSuggest, getArticle } from '@/modules/knowledge/service';
import { impact as ciImpact } from '@/modules/cmdb/service';
import { llmJson, enabled, asSteps, type Steps } from './service';
import { assertFeature } from './guards';
import { SUMMARIZE_SYSTEM, CLASSIFY_SYSTEM, DRAFT_SYSTEM, MAJOR_UPDATE_SYSTEM, RESOLUTION_SYSTEM, RERANK_SYSTEM, IMPACT_SYSTEM, CLUSTER_SYSTEM } from './prompts';
import { compactDetail, compactTimeline, ticketLink } from './tools';

/**
 * AI-assisted ITSM features. Every result is stored as an `ai_suggestions`
 * row (status proposed) and applied only when a human accepts it through the
 * normal ticket endpoints. Each feature has a deterministic fallback used when
 * no provider is configured, so the UI always gets a sane structure.
 *
 * Each feature runs as gather → model → store: the database work happens in
 * short steps (`Steps.tx`) and the model call in between holds no connection.
 * Called with a plain `Ctx` (tests, tools) the steps share that ctx's
 * transaction instead.
 */
type Who = Ctx | Steps;

const trunc = (s: string | null | undefined, n: number) => (s ? (s.length > n ? `${s.slice(0, n)}…` : s) : '');
const firstName = (name?: string | null) => (name ? name.split(/\s+/)[0]! : '');
const minutesLabel = (m: number) => (Math.abs(m) >= 120 ? `${Math.round(Math.abs(m) / 60)}h` : `${Math.abs(m)}m`);

export type SuggestionKind = 'summary' | 'classification' | 'assignment' | 'similar' | 'knowledge' | 'resolution' | 'draft_update' | 'duplicates' | 'change_impact' | 'problem_cluster';

async function store(ctx: Ctx, input: { customerId: string | null; entityType: string; entityId: string; kind: SuggestionKind; payload: Record<string, unknown>; rationale?: string | null; confidence?: number | null }) {
  const [row] = await ctx.tx
    .insert(schema.aiSuggestions)
    .values({ customerId: input.customerId, entityType: input.entityType, entityId: input.entityId, kind: input.kind, payload: input.payload, rationale: input.rationale ?? null, confidence: input.confidence ?? null, status: 'proposed' })
    .returning({ id: schema.aiSuggestions.id });
  return row!.id;
}

async function readTicket(ctx: Ctx, id: string) {
  const row = await loadTicket(ctx, id);
  ctx.require(isCustomerUser(ctx) ? 'portal:tickets' : 'tickets:read', row.customerId);
  const detail = await getTicket(ctx, id);
  return { row, detail };
}

// ---------------------------------------------------------------- summarize

const summarySchema = z.object({ summary: z.string().min(1).max(2000), keyFacts: z.array(z.string().max(300)).max(10), nextSteps: z.array(z.string().max(300)).max(8) });

export async function summarize(who: Who, ticketId: string) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'summarize');
    const { row, detail } = await readTicket(ctx, ticketId);
    const tl = await timeline(ctx, ticketId);
    return { row, detail, items: tl.items, compact: compactDetail(ctx, detail), recent: compactTimeline(tl.items, 12) };
  });
  const llm = await llmJson(SUMMARIZE_SYSTEM, JSON.stringify({ ticket: g.compact, timeline: g.recent }), (v) => summarySchema.parse(v));
  const payload = llm?.data ?? fallbackSummary(g.detail, g.items);
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: g.row.customerId, entityType: 'ticket', entityId: g.row.id, kind: 'summary', payload, rationale: llm ? 'Generated by the AI provider from the ticket and its timeline' : 'Rule-based summary (AI provider not configured)' });
    return { suggestionId, aiGenerated: !!llm, ...payload };
  });
}

type Detail = Awaited<ReturnType<typeof getTicket>>;
type TimelineItems = Awaited<ReturnType<typeof timeline>>['items'];

function fallbackSummary(d: Detail, items: TimelineItems): z.infer<typeof summarySchema> {
  const worst = d.sla;
  const owner = d.assignee?.name ? `${d.assignee.name}${d.team ? ` (${d.team.name})` : ''}` : d.team?.name ?? 'nobody yet';
  const summary = `${d.number} is a ${d.priority?.label ?? 'unprioritised'} ${d.typeLabel.toLowerCase()} for ${d.customer?.name ?? 'an unknown customer'}: "${d.title}". It is ${d.status?.label?.toLowerCase() ?? 'in an unknown state'} and assigned to ${owner}.${worst ? ` The ${worst.metric} SLA is ${worst.breached ? 'breached' : worst.paused ? 'paused' : `running (${worst.pctConsumed}% consumed, ${worst.remainingMinutes >= 0 ? `${minutesLabel(worst.remainingMinutes)} left` : `${minutesLabel(worst.remainingMinutes)} overdue`})`}.` : ''}`;
  const keyFacts: string[] = [];
  keyFacts.push(`Opened ${d.createdAt.toISOString().slice(0, 16).replace('T', ' ')} UTC${d.createdByUser ? ` by ${d.createdByUser.name}` : ''}`);
  if (d.site?.name || d.service?.name) keyFacts.push([d.site?.name ? `Site: ${d.site.name}` : null, d.service?.name ? `Service: ${d.service.name}` : null].filter(Boolean).join(' · '));
  if (d.category?.label) keyFacts.push(`Category: ${d.category.label}${d.subcategory?.label ? ` / ${d.subcategory.label}` : ''}`);
  if (d.cis.length) keyFacts.push(`Affected CIs: ${d.cis.map((c) => c.name).join(', ')}`);
  keyFacts.push(`Scope: ${d.scopeStatus.replace(/_/g, ' ')}${d.contract ? ` (${d.contract.number})` : ''}`);
  if (d.isMajor) keyFacts.push('Flagged as a major incident');
  if (d.escalationLevel > 0) keyFacts.push(`Escalated to level ${d.escalationLevel}`);
  const comments = items.filter((i) => i.kind === 'comment').slice(-3);
  for (const c of comments) keyFacts.push(`${c.isInternal ? 'Work note' : 'Comment'} by ${c.actorName ?? 'unknown'}: ${trunc(c.body?.replace(/\s+/g, ' '), 140)}`);
  if (d.resolutionNotes) keyFacts.push(`Resolution: ${trunc(d.resolutionNotes.replace(/\s+/g, ' '), 160)}`);
  const nextSteps: string[] = [];
  const cat = d.status?.category;
  if (cat === 'resolved') nextSteps.push('Confirm the fix with the requester and close the ticket');
  else if (cat === 'closed' || cat === 'cancelled') nextSteps.push('No action required');
  else {
    if (!d.assigneeId) nextSteps.push('Assign an owner (engineer or team)');
    if (!d.firstResponseAt) nextSteps.push('Send a first response to the requester');
    if (worst && (worst.breached || worst.pctConsumed >= 75)) nextSteps.push(`Prioritise: ${worst.metric} SLA ${worst.breached ? 'is breached' : `due in ${minutesLabel(worst.remainingMinutes)}`}`);
    if (cat === 'pending') nextSteps.push('Follow up on the pending item (customer / vendor) and resume work');
    if (!d.category) nextSteps.push('Set a category to improve routing and reporting');
    if (!nextSteps.length) nextSteps.push('Continue diagnosis and post a progress update');
  }
  return { summary, keyFacts: keyFacts.slice(0, 8), nextSteps: nextSteps.slice(0, 5) };
}

// ---------------------------------------------------------------- classification

const classificationSchema = z.object({ categoryKey: z.string().nullable(), subcategoryKey: z.string().nullable(), impactKey: z.string().nullable(), urgencyKey: z.string().nullable(), priorityKey: z.string().nullable(), confidence: z.number().min(0).max(100), rationale: z.string().max(600) });
export type Classification = z.infer<typeof classificationSchema> & { categoryId: string | null; subcategoryId: string | null; impactId: string | null; urgencyId: string | null; priorityId: string | null; labels: Record<string, string | null> };

const KEYWORDS: Record<string, string[]> = {
  network: ['network', 'switch', 'router', 'wan', 'link down', 'vpn', 'wifi', 'wireless', 'lan', 'isp', 'packet loss', 'bgp', 'ospf', 'vlan', 'port'],
  server: ['server', 'windows server', 'linux', 'reboot', 'cpu', 'memory', 'service down', 'iis', 'sql server', 'host', 'patch'],
  storage: ['storage', 'san', 'nas', 'volume', 'capacity', 'disk full', 'lun', 'raid'],
  backup: ['backup', 'restore', 'veeam', 'job failed', 'job failure', 'snapshot', 'retention', 'tape'],
  virtualization: ['vmware', 'esxi', 'vcenter', 'hyper-v', 'virtual machine', 'vm '],
  connectivity: ['cannot connect', 'unreachable', 'no internet', 'internet down', 'connectivity', 'latency', 'timeout'],
  hardware: ['hardware', 'psu', 'power supply', 'fan', 'failed disk', 'replace', 'physical'],
  performance: ['slow', 'performance', 'degraded', 'high utilisation', 'high utilization', 'lag'],
  availability: ['outage', 'unavailable', 'down', 'not responding', 'offline'],
  cloud: ['aws', 'azure', 'gcp', 'cloud', 'o365', 'm365', 'office 365', 'saas'],
  security_incident: ['security incident', 'breach', 'compromise', 'ransomware', 'incident response'],
  malware: ['malware', 'virus', 'trojan', 'ransomware', 'infected'],
  phishing: ['phishing', 'suspicious email', 'spoof', 'scam email'],
  authentication: ['login failure', 'brute force', 'mfa', 'authentication', 'failed logins'],
  firewall: ['firewall', 'fortigate', 'palo alto', 'ips', 'blocked', 'nat rule'],
  endpoint_security: ['edr', 'antivirus', 'endpoint', 'quarantine'],
  vulnerability: ['vulnerability', 'cve', 'patch missing', 'exposure'],
  suspicious_activity: ['suspicious', 'anomal', 'unusual activity', 'siem alert'],
  policy_violation: ['policy violation', 'usb', 'unauthorised software', 'unauthorized software', 'dlp'],
  preventive_maintenance: ['preventive maintenance', 'pm visit', 'scheduled maintenance', 'health check visit'],
  breakdown_support: ['breakdown', 'amc', 'on-site repair', 'onsite repair'],
  site_visit: ['site visit', 'visit', 'engineer on site'],
  hardware_support: ['hardware support', 'spare', 'rma', 'warranty'],
  access: ['access', 'account', 'password reset', 'password', 'login', 'permission', 'locked out', 'unlock', 'new user', 'onboarding'],
  software: ['install', 'software', 'application', 'license', 'licence', 'upgrade', 'app crash'],
  email_collab: ['email', 'outlook', 'mailbox', 'exchange', 'teams', 'sharepoint', 'onedrive', 'calendar'],
  end_user_device: ['laptop', 'desktop', 'printer', 'monitor', 'keyboard', 'mouse', 'docking', 'phone', 'mobile'],
};
/** Phrases and words ending in "!" count double (strong signal). */
const HIGH_IMPACT = ['all users', 'everyone', 'entire!', 'whole site', 'site down', 'outage!', 'multiple users', 'several users', 'many users', 'department', 'company-wide', 'production!', 'all sites', 'business stopped', 'team'];
const LOW_IMPACT = ['one user', 'single user', 'my laptop', 'my account', 'my pc', 'only me', 'cosmetic!'];
const HIGH_URGENCY = ['urgent!', 'immediately!', 'asap!', 'critical!', 'outage!', 'down', 'not working', 'stopped', 'cannot work', 'emergency!', 'p1!', 'major!', 'clicked the link'];
const LOW_URGENCY = ['when possible', 'no rush', 'low priority', 'whenever!', 'nice to have', 'planning!', 'question'];

function scoreKeywords(text: string, words: string[]) {
  let score = 0;
  for (const raw of words) {
    const strong = raw.endsWith('!');
    const w = strong ? raw.slice(0, -1) : raw;
    if (text.includes(w)) score += strong || w.includes(' ') ? 2 : 1;
  }
  return score;
}

/** Crude stemmer so "failed" / "failure" / "failing" match a "Job Failure" label. */
const stem = (w: string) => w.toLowerCase().replace(/(ing|ures?|ed|es|s)$/, '');
const textStems = (text: string) => new Set(text.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2).map(stem));
/** Fraction of the label's significant words whose stem appears in the text (0..1), weighted ×2 to be comparable with phrase hits. */
function scoreLabel(stems: Set<string>, label: string) {
  const words = label.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2 && !['and', 'the', 'for'].includes(w));
  if (!words.length) return 0;
  const hits = words.filter((w) => stems.has(stem(w))).length;
  return hits === words.length ? 2 : hits > 0 ? hits / words.length : 0;
}

async function priorityFromMatrix(ctx: Ctx, impactId: string | null, urgencyId: string | null) {
  if (!impactId || !urgencyId) return null;
  const [cell] = await ctx.tx.select().from(schema.priorityMatrix).where(and(eq(schema.priorityMatrix.impactId, impactId), eq(schema.priorityMatrix.urgencyId, urgencyId))).limit(1);
  return cell ? await optionById(ctx.tx, cell.priorityId) : null;
}

type ClassifyInput = { title: string; description?: string | null; type?: string | null; domainHint?: string | null };
type Gathered = Awaited<ReturnType<typeof gatherClassification>>;

/** Step 1 (database): the option lists and the deterministic heuristic, which is also the fallback. */
async function gatherClassification(ctx: Ctx, input: ClassifyInput) {
  const [categories, subcategories, impacts, urgencies, priorities] = await Promise.all([optionsOfType(ctx.tx, 'ticket_category'), optionsOfType(ctx.tx, 'ticket_subcategory'), optionsOfType(ctx.tx, 'ticket_impact'), optionsOfType(ctx.tx, 'ticket_urgency'), optionsOfType(ctx.tx, 'ticket_priority')]);
  const active = (o: OptionRow) => o.isActive;
  const cats = categories.filter(active);
  const subs = subcategories.filter(active);
  const text = `${input.title}\n${input.description ?? ''}`.toLowerCase();

  // deterministic heuristic first (also the fallback)
  const scored = cats
    .map((c) => ({ c, score: scoreKeywords(text, [...(KEYWORDS[c.key] ?? []), c.label.toLowerCase()]) + (input.domainHint && c.domain === input.domainHint ? 0.5 : 0) }))
    .sort((a, b) => b.score - a.score);
  const bestCat = scored[0] && scored[0].score > 0 ? scored[0].c : null;
  const stems = textStems(text);
  const sub = bestCat ? subs.filter((s) => s.parentId === bestCat.id).map((s) => ({ s, score: scoreKeywords(text, [s.label.toLowerCase()]) + scoreLabel(stems, s.label) })).sort((a, b) => b.score - a.score)[0] : undefined;
  const bestSub = sub && sub.score >= 1 ? sub.s : null;
  const impactScore = scoreKeywords(text, HIGH_IMPACT) - scoreKeywords(text, LOW_IMPACT);
  const urgencyScore = scoreKeywords(text, HIGH_URGENCY) - scoreKeywords(text, LOW_URGENCY);
  const pickLevel = (opts: OptionRow[], s: number) => {
    const act = opts.filter(active).sort((a, b) => (a.level ?? 0) - (b.level ?? 0));
    if (!act.length) return null;
    if (s >= 2) return act[0]!;
    if (s <= -1) return act[act.length - 1]!;
    return act.find((o) => o.isDefault) ?? act[Math.floor(act.length / 2)]!;
  };
  const impact = pickLevel(impacts, impactScore);
  const urgency = pickLevel(urgencies, urgencyScore);
  const matrixPriority = await priorityFromMatrix(ctx, impact?.id ?? null, urgency?.id ?? null);
  const priority = matrixPriority ?? priorities.find((p) => p.isDefault && p.isActive) ?? null;
  const heuristic: Classification = {
    categoryKey: bestCat?.key ?? null,
    subcategoryKey: bestSub?.key ?? null,
    impactKey: impact?.key ?? null,
    urgencyKey: urgency?.key ?? null,
    priorityKey: priority?.key ?? null,
    confidence: Math.min(90, 35 + (scored[0]?.score ?? 0) * 12 + (bestSub ? 10 : 0)),
    rationale: bestCat ? `Keywords match "${bestCat.label}"${bestSub ? ` / ${bestSub.label}` : ''}; impact ${impact?.key ?? '-'} × urgency ${urgency?.key ?? '-'} → ${priority?.label ?? 'default priority'} from the priority matrix.` : 'No category keywords matched; priority inputs default to medium.',
    categoryId: bestCat?.id ?? null,
    subcategoryId: bestSub?.id ?? null,
    impactId: impact?.id ?? null,
    urgencyId: urgency?.id ?? null,
    priorityId: priority?.id ?? null,
    labels: { category: bestCat?.label ?? null, subcategory: bestSub?.label ?? null, impact: impact?.label ?? null, urgency: urgency?.label ?? null, priority: priority?.label ?? null },
  };
  const options = {
    categories: cats.map((c) => ({ key: c.key, label: c.label, domain: c.domain, subcategories: subs.filter((s) => s.parentId === c.id).map((s) => ({ key: s.key, label: s.label })) })),
    impact: impacts.filter(active).map((o) => ({ key: o.key, label: o.label })),
    urgency: urgencies.filter(active).map((o) => ({ key: o.key, label: o.label })),
    priority: priorities.filter(active).map((o) => ({ key: o.key, label: o.label })),
  };
  return { input, heuristic, options, cats, subs, impacts, urgencies, priorities, impact, urgency, priority };
}

/** Step 2 (model, no transaction): the provider's pick from the real option keys; null when disabled or unusable. */
async function classifyLlm(g: Gathered) {
  if (!enabled()) return null;
  return llmJson(CLASSIFY_SYSTEM, JSON.stringify({ ticket: { type: g.input.type ?? 'incident', title: g.input.title, description: trunc(g.input.description, 4000) }, options: g.options }), (v) => classificationSchema.parse(v), { maxTokens: 400 });
}

/** Step 3 (database): resolve the model's keys against the options and the priority matrix, or keep the heuristic. */
async function finishClassification(ctx: Ctx, g: Gathered, llm: Awaited<ReturnType<typeof classifyLlm>>): Promise<{ result: Classification; aiGenerated: boolean }> {
  if (!llm) return { result: g.heuristic, aiGenerated: false };
  const { cats, subs, impacts, urgencies, priorities } = g;
  const cat = cats.find((c) => c.key === llm.data.categoryKey) ?? null;
  const subc = cat ? subs.find((s) => s.parentId === cat.id && s.key === llm.data.subcategoryKey) ?? null : null;
  const imp = impacts.find((o) => o.key === llm.data.impactKey && o.isActive) ?? g.impact;
  const urg = urgencies.find((o) => o.key === llm.data.urgencyKey && o.isActive) ?? g.urgency;
  const prio = (await priorityFromMatrix(ctx, imp?.id ?? null, urg?.id ?? null)) ?? priorities.find((p) => p.key === llm.data.priorityKey && p.isActive) ?? g.priority;
  return {
    aiGenerated: true,
    result: {
      categoryKey: cat?.key ?? null,
      subcategoryKey: subc?.key ?? null,
      impactKey: imp?.key ?? null,
      urgencyKey: urg?.key ?? null,
      priorityKey: prio?.key ?? null,
      confidence: Math.round(llm.data.confidence),
      rationale: llm.data.rationale,
      categoryId: cat?.id ?? null,
      subcategoryId: subc?.id ?? null,
      impactId: imp?.id ?? null,
      urgencyId: urg?.id ?? null,
      priorityId: prio?.id ?? null,
      labels: { category: cat?.label ?? null, subcategory: subc?.label ?? null, impact: imp?.label ?? null, urgency: urg?.label ?? null, priority: prio?.label ?? null },
    },
  };
}

export async function classify(who: Who, ticketId: string) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'classify');
    const { row, detail } = await readTicket(ctx, ticketId);
    return { row, gathered: await gatherClassification(ctx, { title: row.title, description: row.description, type: row.type, domainHint: detail.service?.key ? null : row.domain }) };
  });
  const llm = await classifyLlm(g.gathered);
  return s.tx(async (ctx) => {
    const { result, aiGenerated } = await finishClassification(ctx, g.gathered, llm);
    const { row } = g;
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'classification', payload: result as unknown as Record<string, unknown>, rationale: result.rationale, confidence: result.confidence });
    return { suggestionId, aiGenerated, current: { categoryId: row.categoryId, subcategoryId: row.subcategoryId, impactId: row.impactId, urgencyId: row.urgencyId, priorityId: row.priorityId }, ...result };
  });
}

/** Classification for a ticket that does not exist yet (create form). Nothing is stored. */
export async function classifyDraft(who: Who, input: { title: string; description?: string | null; customerId?: string; type?: string }) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'classify');
    if (input.customerId) ctx.requireCustomer(input.customerId);
    return gatherClassification(ctx, { title: input.title, description: input.description, type: input.type });
  });
  const llm = await classifyLlm(g);
  return s.tx(async (ctx) => {
    const { result, aiGenerated } = await finishClassification(ctx, g, llm);
    return { aiGenerated, ...result };
  });
}

// ---------------------------------------------------------------- assignment

export const recommendAssignment = (who: Who, ticketId: string) => asSteps(who).tx((ctx) => recommendAssignmentIn(ctx, ticketId));

async function recommendAssignmentIn(ctx: Ctx, ticketId: string) {
  await assertFeature(ctx, 'assign');
  const { row, detail } = await readTicket(ctx, ticketId);
  if (isCustomerUser(ctx)) throw new ForbiddenError();
  const rule = await evaluateAssignment(ctx.tx, { ticketType: row.type, categoryId: row.categoryId, serviceId: row.serviceId, customerId: row.customerId, priorityId: row.priorityId, domain: row.domain, sourceId: row.sourceId, contractTeamId: null });
  const since = new Date(Date.now() - 90 * 86_400_000);
  // Engineers who resolved similar work for this customer recently, with their current open load.
  const candidates = await ctx.tx.execute(sql`
    WITH resolved AS (
      SELECT t.assignee_id AS user_id,
             count(*) FILTER (WHERE t.customer_id = ${row.customerId}::uuid)::int AS same_customer,
             count(*) FILTER (WHERE ${row.categoryId ? sql`t.category_id = ${row.categoryId}::uuid` : sql`false`})::int AS same_category,
             count(*)::int AS total
      FROM tickets t
      WHERE t.assignee_id IS NOT NULL AND t.resolved_at >= ${since} AND t.type = ${row.type}
      GROUP BY t.assignee_id
    ), load AS (
      SELECT t.assignee_id AS user_id, count(*)::int AS open_load
      FROM tickets t JOIN config_options s ON s.id = t.status_id
      WHERE t.assignee_id IS NOT NULL AND s.status_category IN ('new','open','pending')
      GROUP BY t.assignee_id
    )
    SELECT u.id, u.name, u.email, coalesce(r.same_customer, 0) AS "sameCustomer", coalesce(r.same_category, 0) AS "sameCategory", coalesce(r.total, 0) AS "resolved90d", coalesce(l.open_load, 0) AS "openLoad",
           (SELECT array_agg(tm.team_id) FROM team_members tm WHERE tm.user_id = u.id) AS "teamIds"
    FROM users u
    LEFT JOIN resolved r ON r.user_id = u.id
    LEFT JOIN load l ON l.user_id = u.id
    WHERE u.user_type = 'msp' AND u.status = 'active'
    ORDER BY coalesce(r.same_category, 0) + coalesce(r.same_customer, 0) * 2 DESC, coalesce(l.open_load, 0) ASC, coalesce(r.total, 0) DESC
    LIMIT 25`);
  const rows = candidates.rows as { id: string; name: string; email: string; sameCustomer: number; sameCategory: number; resolved90d: number; openLoad: number; teamIds: string[] | null }[];
  const teams = await ctx.tx.select({ id: schema.teams.id, key: schema.teams.key, name: schema.teams.name }).from(schema.teams).where(eq(schema.teams.isActive, true));
  const teamOf = (id: string | null | undefined) => teams.find((t) => t.id === id) ?? null;

  let teamId: string | null = rule.teamId;
  let userId: string | null = rule.userId;
  const reasons: string[] = [];
  if (rule.source === 'rule') reasons.push(`Assignment rule "${rule.ruleName}" matches this ticket`);
  else if (rule.source === 'service') reasons.push(`Default team of service ${detail.service?.name ?? ''}`);
  if (!teamId && detail.cis.length) {
    const [ci] = await ctx.tx.select({ ownerTeamId: schema.cis.ownerTeamId }).from(schema.cis).where(eq(schema.cis.id, detail.cis[0]!.id)).limit(1);
    if (ci?.ownerTeamId) {
      teamId = ci.ownerTeamId;
      reasons.push(`Owner team of the affected CI ${detail.cis[0]!.name}`);
    }
  }
  if (!userId) {
    const pool = rows.filter((r) => (r.sameCustomer > 0 || r.sameCategory > 0) && (!teamId || (r.teamIds ?? []).includes(teamId)));
    const pick = pool[0] ?? (teamId ? rows.filter((r) => (r.teamIds ?? []).includes(teamId!)).sort((a, b) => a.openLoad - b.openLoad)[0] : undefined);
    if (pick) {
      userId = pick.id;
      if (pick.sameCategory || pick.sameCustomer) reasons.push(`${pick.name} resolved ${pick.sameCategory} ticket(s) in this category and ${pick.sameCustomer} for this customer in the last 90 days, with ${pick.openLoad} open ticket(s) now`);
      else reasons.push(`${pick.name} has the lowest open load (${pick.openLoad}) in the team`);
      if (!teamId && pick.teamIds?.length) teamId = pick.teamIds[0]!;
    }
  }
  const user = userId ? (rows.find((r) => r.id === userId) ?? (await ctx.tx.select({ id: schema.users.id, name: schema.users.name, email: schema.users.email }).from(schema.users).where(eq(schema.users.id, userId)).limit(1))[0]) : null;
  const team = teamOf(teamId);
  const payload = {
    teamKey: team?.key ?? null,
    teamId: team?.id ?? null,
    teamName: team?.name ?? null,
    userId: user?.id ?? null,
    userName: user?.name ?? null,
    rationale: reasons.join('. ') || 'No rule, service default or recent resolver found; assign manually.',
    source: rule.source,
    alternatives: rows.slice(0, 5).map((r) => ({ userId: r.id, name: r.name, resolvedSimilar: r.sameCategory, resolvedForCustomer: r.sameCustomer, openLoad: r.openLoad })),
    current: { teamId: row.assignedTeamId, assigneeId: row.assigneeId },
  };
  const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'assignment', payload, rationale: payload.rationale, confidence: user ? 70 : team ? 50 : 20 });
  return { suggestionId, aiGenerated: false, ...payload };
}

// ---------------------------------------------------------------- similar / knowledge (optional LLM re-ranking)

const rerankSchema = z.object({ ranked: z.array(z.object({ id: z.string(), reason: z.string().max(300) })).max(20), rationale: z.string().max(600) });

export async function similar(who: Who, ticketId: string) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'similar');
    const { row } = await readTicket(ctx, ticketId);
    const res = await similarTickets(ctx, ticketId);
    return { row, items: res.items.map((x) => ({ ...x, link: ticketLink(ctx, x.id), reason: x.sameCustomer ? 'Same customer, similar title' : 'Similar title / content' })) };
  });
  const { row } = g;
  let items = g.items;
  let rationale = `${items.length} tickets ranked by full-text and title similarity; same-customer matches first.`;
  let aiGenerated = false;
  if (items.length > 1) {
    const llm = await llmJson(RERANK_SYSTEM, JSON.stringify({ ticket: { number: row.number, title: row.title, description: trunc(row.description, 1500) }, candidates: items.map((i) => ({ id: i.id, number: i.number, title: i.title, status: i.status?.label, sameCustomer: i.sameCustomer, resolutionNotes: trunc(i.resolutionNotes, 300) })) }), (v) => rerankSchema.parse(v), { maxTokens: 700 });
    if (llm) {
      const order = new Map(llm.data.ranked.map((r, i) => [r.id, { i, reason: r.reason }]));
      items = [...items].sort((a, b) => (order.get(a.id)?.i ?? 99) - (order.get(b.id)?.i ?? 99)).map((i) => ({ ...i, reason: order.get(i.id)?.reason ?? i.reason }));
      rationale = llm.data.rationale;
      aiGenerated = true;
    }
  }
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'similar', payload: { items: items.map((i) => ({ id: i.id, number: i.number, reason: i.reason })) }, rationale });
    return { suggestionId, aiGenerated, items, rationale };
  });
}

export async function suggestKnowledge(who: Who, ticketId: string) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'suggest_kb');
    const { row, detail } = await readTicket(ctx, ticketId);
    const res = await kbSuggest(ctx, { q: `${row.title} ${trunc(row.description, 300)}`.trim(), customerId: row.customerId, serviceId: row.serviceId ?? undefined, limit: 8 });
    return { row, detail, items: res.items.map((a) => ({ ...a, link: `/knowledge/${a.id}`, reason: 'Matches the ticket title / description' })) };
  });
  const { row, detail } = g;
  let items = g.items;
  let rationale = `${items.length} published articles matched by full-text search${detail.service?.name ? `, boosted for service ${detail.service.name}` : ''}.`;
  let aiGenerated = false;
  if (items.length > 1) {
    const llm = await llmJson(RERANK_SYSTEM, JSON.stringify({ ticket: { title: row.title, description: trunc(row.description, 1500) }, candidates: items.map((a) => ({ id: a.id, number: a.number, title: a.title, summary: a.summary, type: a.articleType })) }), (v) => rerankSchema.parse(v), { maxTokens: 700 });
    if (llm) {
      const order = new Map(llm.data.ranked.map((r, i) => [r.id, { i, reason: r.reason }]));
      items = [...items].sort((a, b) => (order.get(a.id)?.i ?? 99) - (order.get(b.id)?.i ?? 99)).map((a) => ({ ...a, reason: order.get(a.id)?.reason ?? a.reason }));
      rationale = llm.data.rationale;
      aiGenerated = true;
    }
  }
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'knowledge', payload: { items: items.map((a) => ({ id: a.id, number: a.number, reason: a.reason })) }, rationale });
    return { suggestionId, aiGenerated, items, rationale };
  });
}

// ---------------------------------------------------------------- resolution suggestions

const resolutionSchema = z.object({ suggestions: z.array(z.object({ source: z.enum(['ticket', 'kb']), ref: z.string().max(60), title: z.string().max(300), steps: z.array(z.string().max(400)).max(8) })).max(6) });

const splitSteps = (text: string, max = 6) =>
  text
    .split(/\r?\n+|(?<=[.!?])\s+(?=[A-Z0-9])/)
    .map((s) => s.replace(/^[-*\d.)\s]+/, '').trim())
    .filter((s) => s.length > 8)
    .slice(0, max);

export async function resolutionSuggestions(who: Who, ticketId: string) {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'resolution');
    const { row } = await readTicket(ctx, ticketId);
    const sim = await similarTickets(ctx, ticketId);
    const resolved = sim.items.filter((x) => x.resolutionNotes && x.resolutionNotes.trim().length > 10).slice(0, 5).map((x) => ({ ...x, link: ticketLink(ctx, x.id) }));
    const kb = await kbSuggest(ctx, { q: row.title, customerId: row.customerId, serviceId: row.serviceId ?? undefined, limit: 4 });
    const articles: { id: string; number: string; title: string; summary: string | null; body: string }[] = [];
    for (const a of kb.items.slice(0, 3)) {
      try {
        const full = await getArticle(ctx, a.id, { noView: true });
        articles.push({ id: a.id, number: a.number, title: a.title, summary: a.summary, body: trunc(full.body, 2500) });
      } catch {
        /* not visible */
      }
    }
    return { row, resolved, articles };
  });
  const { row, resolved, articles } = g;
  const fallback = {
    suggestions: [
      ...resolved.map((x) => ({ source: 'ticket' as const, ref: x.number, title: x.title, steps: splitSteps(x.resolutionNotes!), link: x.link })),
      ...articles.map((a) => ({ source: 'kb' as const, ref: a.number, title: a.title, steps: splitSteps(a.body || a.summary || '', 5), link: `/knowledge/${a.id}` })),
    ].slice(0, 5),
  };
  const llm = resolved.length || articles.length
    ? await llmJson(RESOLUTION_SYSTEM, JSON.stringify({ ticket: { number: row.number, title: row.title, description: trunc(row.description, 2000) }, resolvedTickets: resolved.map((x) => ({ number: x.number, title: x.title, resolutionNotes: trunc(x.resolutionNotes, 1200) })), articles }), (v) => resolutionSchema.parse(v), { maxTokens: 1200 })
    : null;
  const links = new Map<string, string>([...resolved.map((x) => [x.number, x.link] as const), ...articles.map((a) => [a.number, `/knowledge/${a.id}`] as const)]);
  const payload = llm ? { suggestions: llm.data.suggestions.map((x) => ({ ...x, link: links.get(x.ref) ?? null })) } : fallback;
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'resolution', payload, rationale: llm ? 'Synthesised from resolved similar tickets and knowledge articles' : 'Extracted from resolution notes of similar tickets and matching articles' });
    return { suggestionId, aiGenerated: !!llm, ...payload, sources: { resolvedTickets: resolved.length, articles: articles.length } };
  });
}

// ---------------------------------------------------------------- customer update draft

const draftSchema = z.object({ draft: z.string().min(10).max(3000) });

export async function draftCustomerUpdate(who: Who, ticketId: string, tone: 'neutral' | 'formal' | 'friendly' | 'apologetic' = 'neutral') {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'draft');
    const { row, detail } = await readTicket(ctx, ticketId);
    if (isCustomerUser(ctx)) throw new ForbiddenError();
    ctx.require('tickets:comment', row.customerId);
    const tl = await timeline(ctx, ticketId);
    const publicItems = tl.items.filter((i) => !i.isInternal);
    return { row, detail, lastPublic: publicItems.filter((i) => i.kind === 'comment').slice(-2), workNotes: tl.items.filter((i) => i.kind === 'comment' && i.isInternal).slice(-3), compact: compactDetail(ctx, detail) };
  });
  const { row, detail, workNotes } = g;
  const engineer = s.principal.name;
  const llm = await llmJson(DRAFT_SYSTEM, JSON.stringify({ tone, ticket: { ...g.compact, description: trunc(row.description, 800) }, requesterFirstName: firstName(detail.requester?.name ?? detail.requesterContact?.name), latestPublicComments: compactTimeline(g.lastPublic, 2), internalProgressNotes: compactTimeline(workNotes, 3), engineer }), (v) => draftSchema.parse(v), { maxTokens: 500 });
  const draft = llm?.data.draft ?? fallbackDraft(detail, tone, engineer, workNotes);
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'draft_update', payload: { draft, tone }, rationale: llm ? 'Drafted by the AI provider from the ticket state and progress notes' : 'Template draft (AI provider not configured)' });
    return { suggestionId, aiGenerated: !!llm, draft, tone };
  });
}

function fallbackDraft(d: Detail, tone: string, engineer: string, notes: TimelineItems) {
  const name = firstName(d.requester?.name ?? d.requesterContact?.name);
  const greeting = tone === 'formal' ? `Dear ${name || 'Customer'},` : `Hello${name ? ` ${name}` : ''},`;
  const opener = tone === 'apologetic' ? 'We are sorry for the inconvenience this issue is causing. ' : '';
  const cat = d.status?.category;
  const stateLine = cat === 'resolved' ? `We believe the issue is now resolved${d.resolutionNotes ? `: ${trunc(d.resolutionNotes.replace(/\s+/g, ' '), 200)}` : ''}.` : cat === 'pending' ? `The ticket is currently ${d.status?.label?.toLowerCase() ?? 'pending'}; we are waiting for the next step before work can continue.` : `Our ${d.team?.name ?? 'engineering'} team is actively working on it${d.assignee ? ` (owner: ${d.assignee.name})` : ''}.`;
  const progress = notes.length ? ` Latest progress: ${trunc(notes[notes.length - 1]!.body?.replace(/\s+/g, ' '), 180)}` : '';
  const next = cat === 'resolved' ? 'Please let us know if the problem persists; otherwise the ticket will be closed automatically.' : d.sla && !d.sla.breached && d.sla.remainingMinutes > 0 ? `Our target for ${d.sla.metric} is ${new Date(d.sla.dueAt).toISOString().slice(0, 16).replace('T', ' ')} UTC and we will update you as soon as there is progress.` : 'We will update you as soon as there is further progress.';
  const closing = tone === 'friendly' ? 'Thanks for your patience!' : 'Kind regards,';
  return `${greeting}\n\n${opener}This is an update on ticket ${d.number} "${d.title}". ${stateLine}${progress} ${next}\n\n${closing}\n${engineer}`;
}

// ---------------------------------------------------------------- major incident stakeholder update

/** Drafts the next stakeholder update (customer audience) or bridge note (internal) of a major incident. */
export async function draftMajorUpdate(who: Who, ticketId: string, audience: 'customer' | 'internal' = 'customer') {
  const s = asSteps(who);
  const g = await s.tx(async (ctx) => {
    await assertFeature(ctx, 'draft');
    const { row, detail } = await readTicket(ctx, ticketId);
    if (isCustomerUser(ctx)) throw new ForbiddenError();
    ctx.require('tickets:major', row.customerId);
    const major = await getMajor(ctx, ticketId);
    const tl = await timeline(ctx, ticketId);
    return { row, detail, major, notes: tl.items.filter((i) => i.kind === 'comment').slice(-4), compact: compactDetail(ctx, detail) };
  });
  const { row, detail, major, notes } = g;
  const previous = major.updates.filter((u) => u.kind === 'stakeholder').slice(0, 2).map((u) => ({ at: u.createdAt, body: trunc(u.body, 400) }));
  const nextUpdate = major.record?.nextUpdateDueAt ? new Date(major.record.nextUpdateDueAt.getTime() + major.record.updateIntervalMinutes * 60_000) : null;
  const updateNumber = major.updates.filter((u) => u.kind === 'stakeholder').length + 1;
  const llm = await llmJson(
    MAJOR_UPDATE_SYSTEM,
    JSON.stringify({ audience, ticket: { ...g.compact, description: trunc(row.description, 600) }, affectedCis: detail.cis.map((c) => c.name).slice(0, 10), children: major.children.length, declaredAt: major.record?.declaredAt, previousUpdates: previous, latestNotes: compactTimeline(notes, 4), updateNumber, nextUpdateExpectedAt: nextUpdate?.toISOString() ?? null, author: s.principal.name }),
    (v) => draftSchema.parse(v),
    { maxTokens: 450 },
  );
  const draft = llm?.data.draft ?? fallbackMajorUpdate(detail, audience, updateNumber, nextUpdate, notes);
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'draft_update', payload: { draft, audience, major: true }, rationale: llm ? 'Drafted by the AI provider from the incident record, the communication log and the latest notes' : 'Template draft (AI provider not configured)' });
    return { suggestionId, aiGenerated: !!llm, draft, audience };
  });
}

function fallbackMajorUpdate(d: Detail, audience: 'customer' | 'internal', n: number, nextUpdate: Date | null, notes: TimelineItems) {
  const latest = notes.length ? trunc(notes[notes.length - 1]!.body?.replace(/\s+/g, ' '), 200) : '';
  const when = nextUpdate ? `${nextUpdate.toISOString().slice(11, 16)} UTC` : 'as soon as there is news';
  const affected = d.cis.length ? ` Affected: ${d.cis.map((c) => c.name).slice(0, 3).join(', ')}.` : '';
  if (audience === 'internal') return `Bridge note ${n} for ${d.number}: ${d.status?.label ?? 'In progress'}, owner ${d.assignee?.name ?? 'unassigned'}.${affected}${latest ? ` Latest: ${latest}` : ''} Next stakeholder update ${when}.`;
  const cat = d.status?.category;
  const state = cat === 'resolved' ? 'Service has been restored and we are monitoring closely.' : 'Our engineers are working on it as the highest priority.';
  return `Update ${n} on major incident ${d.number} "${d.title}".${affected} ${state}${latest ? ` Current status: ${latest}` : ''} The next update will follow by ${when}. We apologise for the disruption.`;
}

// ---------------------------------------------------------------- duplicate check

export const duplicateCheck = (who: Who, ticketId: string) => asSteps(who).tx((ctx) => duplicateCheckIn(ctx, ticketId));

async function duplicateCheckIn(ctx: Ctx, ticketId: string) {
  await assertFeature(ctx, 'duplicates');
  const { row } = await readTicket(ctx, ticketId);
  const conds = [sql`x.id <> ${row.id}::uuid`, sql`x.customer_id = ${row.customerId}::uuid`, sql`x.type = ${row.type}`, sql`s.status_category IN ('new','open','pending')`];
  if (!isCustomerUser(ctx) && !ctx.can('soc:read')) conds.push(sql`x.domain <> 'soc'`);
  const res = await ctx.tx.execute(sql`
    SELECT x.id, x.number, x.title, x.type, x.created_at AS "createdAt", s.label AS "status", x.primary_ci_id AS "primaryCiId",
           similarity(x.title, ${row.title}) AS "titleSimilarity",
           ts_rank(x.search_vector, plainto_tsquery('simple', ${row.title})) AS "rank",
           (x.primary_ci_id IS NOT NULL AND x.primary_ci_id = ${row.primaryCiId ?? null}::uuid) AS "sameCi",
           EXISTS (SELECT 1 FROM ticket_cis a JOIN ticket_cis b ON a.ci_id = b.ci_id WHERE a.ticket_id = x.id AND b.ticket_id = ${row.id}::uuid) AS "sharesCi"
    FROM tickets x JOIN config_options s ON s.id = x.status_id
    WHERE ${sql.join(conds, sql` AND `)}
      AND (similarity(x.title, ${row.title}) > 0.3 OR x.search_vector @@ plainto_tsquery('simple', ${row.title})
           OR (x.primary_ci_id IS NOT NULL AND x.primary_ci_id = ${row.primaryCiId ?? null}::uuid)
           OR EXISTS (SELECT 1 FROM ticket_cis a JOIN ticket_cis b ON a.ci_id = b.ci_id WHERE a.ticket_id = x.id AND b.ticket_id = ${row.id}::uuid))
    ORDER BY similarity(x.title, ${row.title}) DESC, x.created_at DESC
    LIMIT 10`);
  const rows = res.rows as { id: string; number: string; title: string; type: string; createdAt: Date | string; status: string; titleSimilarity: number; rank: number; sameCi: boolean; sharesCi: boolean }[];
  const items = rows
    .map((r) => {
      const ageDays = (Date.now() - new Date(r.createdAt).getTime()) / 86_400_000;
      const score = Math.min(1, Number(r.titleSimilarity) * 0.6 + Math.min(Number(r.rank), 0.5) * 0.4 + (r.sameCi ? 0.3 : r.sharesCi ? 0.2 : 0) + (ageDays <= 7 ? 0.1 : 0));
      const reasons = [Number(r.titleSimilarity) > 0.3 ? `title ${Math.round(Number(r.titleSimilarity) * 100)}% similar` : null, r.sameCi ? 'same primary CI' : r.sharesCi ? 'shares an affected CI' : null, ageDays <= 7 ? 'opened in the last 7 days' : null].filter(Boolean) as string[];
      return { id: r.id, number: r.number, title: r.title, type: r.type, status: r.status, createdAt: new Date(r.createdAt).toISOString(), score: Math.round(score * 100) / 100, reasons, link: ticketLink(ctx, r.id) };
    })
    .filter((i) => i.score >= 0.25)
    .sort((a, b) => b.score - a.score);
  const payload = { items, likely: items.filter((i) => i.score >= 0.6).map((i) => i.number) };
  const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'duplicates', payload, rationale: 'Open tickets of the same customer with similar titles or shared configuration items', confidence: items[0] ? Math.round(items[0].score * 100) : 0 });
  return { suggestionId, aiGenerated: false, ...payload };
}

// ---------------------------------------------------------------- change impact

const impactSchema = z.object({ riskSummary: z.string().min(10).max(2000), riskLevel: z.enum(['low', 'medium', 'high']), recommendations: z.array(z.string().max(300)).max(6) });

export async function changeImpact(who: Who, changeId: string) {
  const s = asSteps(who);
  const g = await s.tx((ctx) => gatherChangeImpact(ctx, changeId));
  const { row, data, fallback, affected, dependents, services, otherChanges } = g;
  const llm = await llmJson(IMPACT_SYSTEM, JSON.stringify(data), (v) => impactSchema.parse(v), { maxTokens: 600 });
  const analysis = llm?.data ?? fallback;
  return s.tx(async (ctx) => {
    const suggestionId = await store(ctx, { customerId: row.customerId, entityType: 'ticket', entityId: row.id, kind: 'change_impact', payload: { ...analysis, affectedCis: affected.map((a) => a.name), dependents: dependents.size, businessServices: [...services], otherChanges: otherChanges.map((o) => o.number) }, rationale: analysis.riskSummary });
    return { suggestionId, aiGenerated: !!llm, ...data, ...analysis };
  });
}

async function gatherChangeImpact(ctx: Ctx, changeId: string) {
  await assertFeature(ctx, 'change_impact');
  const { row, detail } = await readTicket(ctx, changeId);
  if (row.type !== 'change') throw new ValidationError('Impact analysis is only available for change records');
  ctx.require('changes:manage', row.customerId);
  const change = detail.change;
  const affected: { id: string; name: string; type: string | null; criticality: string | null; dependents: number; businessServices: string[]; openTickets: number }[] = [];
  const dependents = new Map<string, { name: string; type: string; criticality: string; via: string; from: string }>();
  const services = new Set<string>();
  const openTickets = new Map<string, { number: string; title: string; status: string; link: string }>();
  for (const ci of detail.cis.slice(0, 10)) {
    try {
      const imp = await ciImpact(ctx, ci.id);
      imp.dependents.forEach((d) => dependents.set(d.id, { name: d.name, type: d.typeName, criticality: d.criticality, via: d.via, from: ci.name }));
      imp.businessServices.forEach((b) => services.add(b.name));
      imp.openTickets.forEach((t) => openTickets.set(t.id, { number: t.number, title: t.title, status: t.status, link: ticketLink(ctx, t.id) }));
      affected.push({ id: ci.id, name: ci.name, type: imp.root.typeName, criticality: imp.root.criticality, dependents: imp.dependents.length, businessServices: imp.businessServices.map((b) => b.name), openTickets: imp.openTickets.length });
    } catch {
      affected.push({ id: ci.id, name: ci.name, type: null, criticality: null, dependents: 0, businessServices: [], openTickets: 0 });
    }
  }
  // Other changes of the customer overlapping the scheduled window (± 1 day when no window is set).
  const start = change?.scheduledStart ? new Date(change.scheduledStart) : new Date();
  const end = change?.scheduledEnd ? new Date(change.scheduledEnd) : new Date(start.getTime() + 86_400_000);
  const windowFrom = new Date(start.getTime() - 86_400_000);
  const windowTo = new Date(end.getTime() + 86_400_000);
  const overlapping = await ctx.tx
    .select({ id: schema.tickets.id, number: schema.tickets.number, title: schema.tickets.title, scheduledStart: schema.changeDetails.scheduledStart, scheduledEnd: schema.changeDetails.scheduledEnd, statusId: schema.tickets.statusId })
    .from(schema.changeDetails)
    .innerJoin(schema.tickets, eq(schema.tickets.id, schema.changeDetails.ticketId))
    .where(and(eq(schema.tickets.customerId, row.customerId), ne(schema.tickets.id, row.id), isNotNull(schema.changeDetails.scheduledStart), sql`${schema.changeDetails.scheduledStart} <= ${windowTo}`, sql`coalesce(${schema.changeDetails.scheduledEnd}, ${schema.changeDetails.scheduledStart} + interval '4 hours') >= ${windowFrom}`))
    .orderBy(schema.changeDetails.scheduledStart)
    .limit(10);
  const statusRows = overlapping.length ? await ctx.tx.select({ id: schema.configOptions.id, label: schema.configOptions.label, category: schema.configOptions.statusCategory }).from(schema.configOptions).where(inArray(schema.configOptions.id, overlapping.map((o) => o.statusId))) : [];
  const otherChanges = overlapping
    .map((o) => ({ id: o.id, number: o.number, title: o.title, scheduledStart: o.scheduledStart?.toISOString() ?? null, scheduledEnd: o.scheduledEnd?.toISOString() ?? null, status: statusRows.find((s) => s.id === o.statusId)?.label ?? null, statusCategory: statusRows.find((s) => s.id === o.statusId)?.category ?? null, link: ticketLink(ctx, o.id) }))
    .filter((o) => !['closed', 'cancelled'].includes(o.statusCategory ?? ''));

  const data = {
    change: { number: row.number, title: row.title, type: change?.changeType ?? null, risk: change?.risk?.label ?? null, scheduledStart: change?.scheduledStart?.toISOString() ?? null, scheduledEnd: change?.scheduledEnd?.toISOString() ?? null, downtimeExpectedMinutes: change?.downtimeExpectedMinutes ?? null, backoutPlan: !!change?.backoutPlan, testPlan: !!change?.testPlan, implementationPlan: trunc(change?.implementationPlan, 600) },
    affectedCis: affected,
    downstream: [...dependents.values()].slice(0, 60),
    businessServices: [...services],
    openTickets: [...openTickets.values()].slice(0, 30),
    otherChanges,
  };
  const critical = [...dependents.values()].filter((d) => d.criticality === 'critical' || d.criticality === 'high').length + affected.filter((a) => a.criticality === 'critical' || a.criticality === 'high').length;
  const heuristicLevel: 'low' | 'medium' | 'high' = services.size > 0 || critical > 0 || (change?.changeType === 'emergency') ? 'high' : dependents.size > 3 || openTickets.size > 0 || otherChanges.length > 0 ? 'medium' : 'low';
  const fallback: z.infer<typeof impactSchema> = {
    riskLevel: heuristicLevel,
    riskSummary: `${row.number} touches ${affected.length} configuration item(s)${affected.length ? ` (${affected.map((a) => a.name).join(', ')})` : ''} with ${dependents.size} downstream dependent CI(s)${services.size ? ` and ${services.size} business service(s): ${[...services].join(', ')}` : ''}. ${openTickets.size ? `${openTickets.size} open ticket(s) already reference the affected items. ` : ''}${otherChanges.length ? `${otherChanges.length} other change(s) are scheduled in the same window (${otherChanges.map((o) => o.number).join(', ')}). ` : ''}${change?.backoutPlan ? 'A backout plan is documented.' : 'No backout plan is documented.'}`,
    recommendations: [
      !change?.backoutPlan ? 'Document a backout plan before approval' : null,
      !change?.testPlan ? 'Add a test / verification plan' : null,
      services.size ? 'Notify business-service owners and schedule within an agreed maintenance window' : null,
      otherChanges.length ? 'Coordinate with the overlapping changes to avoid compounding outages' : null,
      openTickets.size ? 'Review open tickets on the affected CIs; consider linking them to this change' : null,
      !change?.scheduledStart ? 'Set a scheduled start and end' : null,
    ].filter(Boolean) as string[],
  };
  return { row, data, fallback, affected, dependents, services, otherChanges };
}

// ---------------------------------------------------------------- problem clusters

const clusterNamesSchema = z.object({ clusters: z.array(z.object({ key: z.string(), title: z.string().max(120) })).max(60) });
const STOP = new Set(['the', 'a', 'an', 'on', 'in', 'at', 'for', 'to', 'of', 'and', 'or', 'is', 'are', 'with', 'from', 'not', 'no', 'has', 'have', 'been', 'after', 'by', 'issue', 'problem', 'error', 'ticket', 'please', 'again', 'still']);
const tokens = (title: string) => new Set(title.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/\s+/).filter((w) => w.length > 2 && !STOP.has(w) && !/^\d+$/.test(w)));
const jaccard = (a: Set<string>, b: Set<string>) => {
  if (!a.size || !b.size) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter++;
  return inter / (a.size + b.size - inter);
};

export async function problemClusters(who: Who, opts: { days?: number; customerId?: string; minCount?: number } = {}) {
  const s = asSteps(who);
  const g = await s.tx((ctx) => gatherProblemClusters(ctx, opts));
  const { days, minCount, rows, top } = g;
  let aiGenerated = false;
  if (top.length) {
    const llm = await llmJson(CLUSTER_SYSTEM, JSON.stringify({ clusters: top.map((c) => ({ key: c.key, customer: c.customerName, category: c.categoryLabel, ci: c.ciName, count: c.count, titles: c.sampleTickets.map((t) => t.title) })) }), (v) => clusterNamesSchema.parse(v), { maxTokens: 1500 });
    if (llm) {
      const names = new Map(llm.data.clusters.map((c) => [c.key, c.title]));
      for (const c of top) if (names.get(c.key)) c.suggestedTitle = names.get(c.key)!;
      aiGenerated = true;
    }
  }
  return { days, minCount, aiGenerated, totalIncidents: rows.length, clusters: top };
}

async function gatherProblemClusters(ctx: Ctx, opts: { days?: number; customerId?: string; minCount?: number }) {
  await assertFeature(ctx, 'problem_clusters');
  if (isCustomerUser(ctx)) throw new ForbiddenError();
  ctx.require('tickets:read');
  const days = opts.days ?? 30;
  const minCount = opts.minCount ?? 3;
  if (opts.customerId) ctx.requireCustomer(opts.customerId);
  const conds = [sql`t.type = 'incident'`, sql`t.created_at >= now() - make_interval(days => ${days})`];
  if (opts.customerId) conds.push(sql`t.customer_id = ${opts.customerId}::uuid`);
  if (!ctx.can('soc:read')) conds.push(sql`t.domain <> 'soc'`);
  conds.push(sql`NOT EXISTS (SELECT 1 FROM ticket_links l JOIN tickets p ON p.id IN (l.target_ticket_id, l.source_ticket_id) WHERE (l.source_ticket_id = t.id OR l.target_ticket_id = t.id) AND p.type = 'problem')`);
  const res = await ctx.tx.execute(sql`
    SELECT t.id, t.number, t.title, t.created_at AS "createdAt", t.resolved_at AS "resolvedAt",
           t.customer_id AS "customerId", c.name AS "customerName", t.category_id AS "categoryId", co.label AS "categoryLabel",
           t.primary_ci_id AS "primaryCiId", ci.name AS "ciName", s.label AS "status", s.status_category AS "statusCategory", t.service_id AS "serviceId", sv.name AS "serviceName"
    FROM tickets t
    JOIN customers c ON c.id = t.customer_id
    JOIN config_options s ON s.id = t.status_id
    LEFT JOIN config_options co ON co.id = t.category_id
    LEFT JOIN cis ci ON ci.id = t.primary_ci_id
    LEFT JOIN services sv ON sv.id = t.service_id
    WHERE ${sql.join(conds, sql` AND `)}
    ORDER BY t.created_at DESC
    LIMIT 3000`);
  type Row = { id: string; number: string; title: string; createdAt: string; resolvedAt: string | null; customerId: string; customerName: string; categoryId: string | null; categoryLabel: string | null; primaryCiId: string | null; ciName: string | null; status: string; statusCategory: string; serviceId: string | null; serviceName: string | null };
  const rows = res.rows as Row[];
  // 1) group by customer + category + primary CI
  const groups = new Map<string, Row[]>();
  for (const r of rows) {
    const k = `${r.customerId}|${r.categoryId ?? '-'}|${r.primaryCiId ?? '-'}`;
    groups.set(k, [...(groups.get(k) ?? []), r]);
  }
  // 2) within each group, cluster by title token overlap
  const clusters: { key: string; customerId: string; customerName: string; categoryLabel: string | null; ciName: string | null; serviceName: string | null; count: number; openCount: number; firstAt: string; lastAt: string; commonTerms: string[]; suggestedTitle: string; sampleTickets: { id: string; number: string; title: string; status: string; createdAt: string; link: string }[] }[] = [];
  for (const [gk, members] of groups) {
    if (members.length < minCount) continue;
    const buckets: { tokens: Set<string>; items: Row[] }[] = [];
    for (const m of members) {
      const tk = tokens(m.title);
      const hit = buckets.find((b) => jaccard(b.tokens, tk) >= 0.34);
      if (hit) {
        hit.items.push(m);
        tk.forEach((t) => hit.tokens.add(t));
      } else buckets.push({ tokens: new Set(tk), items: [m] });
    }
    // small buckets fold back into the group-level cluster when the CI or category already ties them together
    const big = buckets.filter((b) => b.items.length >= minCount);
    const rest = buckets.filter((b) => b.items.length < minCount).flatMap((b) => b.items);
    const finalBuckets = big.map((b) => b.items);
    if (rest.length >= minCount && (members[0]!.primaryCiId || members[0]!.categoryId)) finalBuckets.push(rest);
    for (const items of finalBuckets) {
      const freq = new Map<string, number>();
      for (const it of items) for (const t of tokens(it.title)) freq.set(t, (freq.get(t) ?? 0) + 1);
      const common = [...freq.entries()].filter(([, n]) => n >= Math.max(2, Math.ceil(items.length / 2))).sort((a, b) => b[1] - a[1]).slice(0, 4).map(([t]) => t);
      const first = items[0]!;
      const sorted = [...items].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      const titleCore = common.length ? common.join(' ') : first.categoryLabel ?? 'incidents';
      const suggestedTitle = `Recurring ${first.categoryLabel ? `${first.categoryLabel.toLowerCase()} ` : ''}incidents${first.ciName ? ` on ${first.ciName}` : ''}: ${titleCore} (${first.customerName})`.slice(0, 120);
      clusters.push({
        key: `${gk}|${sorted[0]!.id}`,
        customerId: first.customerId,
        customerName: first.customerName,
        categoryLabel: first.categoryLabel,
        ciName: first.ciName,
        serviceName: first.serviceName,
        count: items.length,
        openCount: items.filter((i) => ['new', 'open', 'pending'].includes(i.statusCategory)).length,
        firstAt: new Date(sorted[sorted.length - 1]!.createdAt).toISOString(),
        lastAt: new Date(sorted[0]!.createdAt).toISOString(),
        commonTerms: common,
        suggestedTitle,
        sampleTickets: sorted.slice(0, 5).map((i) => ({ id: i.id, number: i.number, title: i.title, status: i.status, createdAt: new Date(i.createdAt).toISOString(), link: ticketLink(ctx, i.id) })),
      });
    }
  }
  clusters.sort((a, b) => b.count - a.count || b.lastAt.localeCompare(a.lastAt));
  return { days, minCount, rows, top: clusters.slice(0, 40) };
}

// ---------------------------------------------------------------- suggestion records

export async function listSuggestions(ctx: Ctx, ticketId: string, kind?: string) {
  const row = await loadTicket(ctx, ticketId);
  // Stored suggestions are produced by staff and carry internal detail (work notes, engineer load, duplicate candidates): never listed in the portal.
  if (isCustomerUser(ctx)) return { items: [] as { id: string; kind: string; status: string; confidence: number | null; rationale: string | null; payload: Record<string, unknown>; decidedBy: string | null; decidedAt: Date | null; createdAt: Date }[] };
  const conds = [eq(schema.aiSuggestions.entityType, 'ticket'), eq(schema.aiSuggestions.entityId, row.id)];
  if (kind) conds.push(eq(schema.aiSuggestions.kind, kind));
  const rows = await ctx.tx.select().from(schema.aiSuggestions).where(and(...conds)).orderBy(desc(schema.aiSuggestions.createdAt)).limit(50);
  return { items: rows.map((s) => ({ id: s.id, kind: s.kind, status: s.status, confidence: s.confidence, rationale: s.rationale, payload: s.payload, decidedBy: s.decidedBy, decidedAt: s.decidedAt, createdAt: s.createdAt })) };
}

export async function decide(ctx: Ctx, suggestionId: string, status: 'accepted' | 'rejected', note?: string | null) {
  const [s] = await ctx.tx.select().from(schema.aiSuggestions).where(eq(schema.aiSuggestions.id, suggestionId)).limit(1);
  if (!s) throw new NotFoundError('Suggestion');
  if (s.customerId) ctx.requireCustomer(s.customerId);
  if (s.entityType === 'ticket') await loadTicket(ctx, s.entityId); // read access to the ticket is enough; applying happens through the ticket endpoints
  const [updated] = await ctx.tx.update(schema.aiSuggestions).set({ status, decidedBy: ctx.user.id, decidedAt: new Date(), payload: note ? { ...s.payload, decisionNote: note } : s.payload }).where(eq(schema.aiSuggestions.id, s.id)).returning();
  await ctx.audit({ entityType: 'ai_suggestion', entityId: s.id, entityLabel: s.kind, action: `ai.suggestion.${status}`, customerId: s.customerId, metadata: { kind: s.kind, entityType: s.entityType, entityId: s.entityId, note: note ?? null } });
  return { id: updated!.id, kind: updated!.kind, status: updated!.status, decidedAt: updated!.decidedAt };
}

export type { TicketRow };
export const _internal = { fallbackSummary, fallbackDraft, splitSteps, tokens, jaccard };
