/**
 * Default configurable option lists. Keys are stable identifiers referenced by
 * code (e.g. status category logic) while labels/colours are editable by
 * administrators. Everything here can be modified or extended in the UI.
 */
export interface OptionSeed {
  key: string;
  label: string;
  description?: string;
  domain?: 'general' | 'noc' | 'soc' | 'amc' | 'service_desk';
  statusCategory?: 'new' | 'open' | 'pending' | 'resolved' | 'closed' | 'cancelled';
  pausesSla?: boolean;
  level?: number;
  color?: string;
  icon?: string;
  appliesTo?: string[];
  parent?: string;
  isDefault?: boolean;
  metadata?: Record<string, unknown>;
}

export const OPTION_SEEDS: Record<string, OptionSeed[]> = {
  ticket_status: [
    { key: 'new', label: 'New', statusCategory: 'new', color: 'blue', isDefault: true },
    { key: 'in_progress', label: 'In Progress', statusCategory: 'open', color: 'indigo' },
    { key: 'pending_customer', label: 'Pending Customer', statusCategory: 'pending', pausesSla: true, color: 'amber' },
    { key: 'pending_vendor', label: 'Pending Vendor', statusCategory: 'pending', pausesSla: true, color: 'amber' },
    { key: 'pending_change', label: 'Pending Change', statusCategory: 'pending', color: 'amber', appliesTo: ['incident', 'problem'] },
    { key: 'on_hold', label: 'On Hold', statusCategory: 'pending', pausesSla: true, color: 'slate' },
    { key: 'resolved', label: 'Resolved', statusCategory: 'resolved', color: 'green' },
    { key: 'closed', label: 'Closed', statusCategory: 'closed', color: 'gray' },
    { key: 'cancelled', label: 'Cancelled', statusCategory: 'cancelled', color: 'gray' },
    // Service requests
    { key: 'awaiting_approval', label: 'Awaiting Approval', statusCategory: 'pending', pausesSla: true, color: 'purple', appliesTo: ['request', 'change'] },
    { key: 'in_fulfilment', label: 'In Fulfilment', statusCategory: 'open', color: 'indigo', appliesTo: ['request'] },
    { key: 'fulfilled', label: 'Fulfilled', statusCategory: 'resolved', color: 'green', appliesTo: ['request'] },
    { key: 'rejected', label: 'Rejected', statusCategory: 'cancelled', color: 'red', appliesTo: ['request', 'change'] },
    // Problems
    { key: 'under_investigation', label: 'Under Investigation', statusCategory: 'open', color: 'indigo', appliesTo: ['problem'] },
    { key: 'root_cause_identified', label: 'Root Cause Identified', statusCategory: 'open', color: 'teal', appliesTo: ['problem'] },
    { key: 'known_error', label: 'Known Error', statusCategory: 'open', color: 'orange', appliesTo: ['problem'] },
    // Changes
    { key: 'draft', label: 'Draft', statusCategory: 'new', color: 'slate', appliesTo: ['change'] },
    { key: 'approved', label: 'Approved', statusCategory: 'open', color: 'teal', appliesTo: ['change'] },
    { key: 'scheduled', label: 'Scheduled', statusCategory: 'open', color: 'cyan', appliesTo: ['change'] },
    { key: 'implementing', label: 'Implementing', statusCategory: 'open', color: 'indigo', appliesTo: ['change'] },
    { key: 'review', label: 'Post-Implementation Review', statusCategory: 'pending', color: 'purple', appliesTo: ['change'] },
    { key: 'implemented', label: 'Implemented', statusCategory: 'resolved', color: 'green', appliesTo: ['change'] },
    { key: 'failed', label: 'Failed / Backed Out', statusCategory: 'resolved', color: 'red', appliesTo: ['change'] },
  ],
  ticket_priority: [
    { key: 'p1', label: 'P1 - Critical', level: 1, color: 'red', description: 'Complete outage of a critical service; business stopped.' },
    { key: 'p2', label: 'P2 - High', level: 2, color: 'orange', description: 'Major degradation; significant business impact.' },
    { key: 'p3', label: 'P3 - Medium', level: 3, color: 'amber', isDefault: true, description: 'Limited impact; workaround available.' },
    { key: 'p4', label: 'P4 - Low', level: 4, color: 'blue', description: 'Minor issue; no business impact.' },
    { key: 'p5', label: 'P5 - Planning', level: 5, color: 'slate', description: 'Scheduled / planned work.' },
  ],
  ticket_impact: [
    { key: 'high', label: 'High - Organization/site wide', level: 1 },
    { key: 'medium', label: 'Medium - Department/multiple users', level: 2, isDefault: true },
    { key: 'low', label: 'Low - Single user', level: 3 },
  ],
  ticket_urgency: [
    { key: 'high', label: 'High - Immediate', level: 1 },
    { key: 'medium', label: 'Medium - Soon', level: 2, isDefault: true },
    { key: 'low', label: 'Low - Can wait', level: 3 },
  ],
  ticket_source: [
    { key: 'portal', label: 'Customer Portal', isDefault: true },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'monitoring', label: 'Monitoring (PRTG)' },
    { key: 'siem', label: 'SIEM (FortiSIEM)' },
    { key: 'engineer', label: 'Engineer' },
    { key: 'field', label: 'Field Visit' },
    { key: 'ai', label: 'AI Assistant' },
    { key: 'api', label: 'API / Integration' },
  ],
  ticket_category: [
    // NOC
    { key: 'network', label: 'Network', domain: 'noc', icon: 'network' },
    { key: 'server', label: 'Server', domain: 'noc', icon: 'server' },
    { key: 'storage', label: 'Storage', domain: 'noc', icon: 'database' },
    { key: 'backup', label: 'Backup', domain: 'noc', icon: 'archive' },
    { key: 'virtualization', label: 'Virtualization', domain: 'noc', icon: 'layers' },
    { key: 'connectivity', label: 'Connectivity', domain: 'noc', icon: 'wifi' },
    { key: 'hardware', label: 'Hardware', domain: 'noc', icon: 'cpu' },
    { key: 'performance', label: 'Performance', domain: 'noc', icon: 'activity' },
    { key: 'availability', label: 'Availability', domain: 'noc', icon: 'heart-pulse' },
    { key: 'cloud', label: 'Cloud', domain: 'noc', icon: 'cloud' },
    // SOC
    { key: 'security_incident', label: 'Security Incident', domain: 'soc', icon: 'shield-alert' },
    { key: 'malware', label: 'Malware', domain: 'soc', icon: 'bug' },
    { key: 'phishing', label: 'Phishing', domain: 'soc', icon: 'mail-warning' },
    { key: 'authentication', label: 'Authentication', domain: 'soc', icon: 'key' },
    { key: 'firewall', label: 'Firewall', domain: 'soc', icon: 'shield' },
    { key: 'endpoint_security', label: 'Endpoint Security', domain: 'soc', icon: 'laptop' },
    { key: 'vulnerability', label: 'Vulnerability', domain: 'soc', icon: 'scan' },
    { key: 'suspicious_activity', label: 'Suspicious Activity', domain: 'soc', icon: 'eye' },
    { key: 'policy_violation', label: 'Policy Violation', domain: 'soc', icon: 'file-warning' },
    // AMC
    { key: 'preventive_maintenance', label: 'Preventive Maintenance', domain: 'amc', icon: 'wrench' },
    { key: 'breakdown_support', label: 'Breakdown Support', domain: 'amc', icon: 'alert-triangle' },
    { key: 'site_visit', label: 'Site Visit', domain: 'amc', icon: 'map-pin' },
    { key: 'hardware_support', label: 'Hardware Support', domain: 'amc', icon: 'hard-drive' },
    { key: 'network_support', label: 'Network Support', domain: 'amc', icon: 'network' },
    { key: 'server_support', label: 'Server Support', domain: 'amc', icon: 'server' },
    { key: 'inspection', label: 'Inspection', domain: 'amc', icon: 'clipboard-check' },
    { key: 'health_check', label: 'Health Check', domain: 'amc', icon: 'stethoscope' },
    // Service desk
    { key: 'access', label: 'Access & Accounts', domain: 'service_desk', icon: 'user-check' },
    { key: 'software', label: 'Software', domain: 'service_desk', icon: 'package' },
    { key: 'email_collab', label: 'Email & Collaboration', domain: 'service_desk', icon: 'mail' },
    { key: 'end_user_device', label: 'End User Device', domain: 'service_desk', icon: 'monitor' },
    { key: 'other', label: 'Other', domain: 'general', icon: 'circle-help' },
  ],
  ticket_subcategory: [
    { key: 'switch', label: 'Switch', parent: 'network' },
    { key: 'router', label: 'Router', parent: 'network' },
    { key: 'wan_link', label: 'WAN Link / ISP', parent: 'network' },
    { key: 'wifi', label: 'Wireless', parent: 'network' },
    { key: 'vpn', label: 'VPN', parent: 'network' },
    { key: 'lan', label: 'LAN', parent: 'network' },
    { key: 'os', label: 'Operating System', parent: 'server' },
    { key: 'server_hardware', label: 'Server Hardware', parent: 'server' },
    { key: 'patching', label: 'Patching', parent: 'server' },
    { key: 'server_performance', label: 'Performance', parent: 'server' },
    { key: 'service_down', label: 'Service Down', parent: 'server' },
    { key: 'capacity', label: 'Capacity', parent: 'storage' },
    { key: 'disk_failure', label: 'Disk Failure', parent: 'storage' },
    { key: 'san', label: 'SAN / Fabric', parent: 'storage' },
    { key: 'job_failure', label: 'Job Failure', parent: 'backup' },
    { key: 'restore', label: 'Restore', parent: 'backup' },
    { key: 'backup_policy', label: 'Policy / Retention', parent: 'backup' },
    { key: 'vm', label: 'Virtual Machine', parent: 'virtualization' },
    { key: 'hypervisor', label: 'Hypervisor', parent: 'virtualization' },
    { key: 'cluster', label: 'Cluster', parent: 'virtualization' },
    { key: 'internet', label: 'Internet', parent: 'connectivity' },
    { key: 'site_to_site', label: 'Site to Site', parent: 'connectivity' },
    { key: 'power', label: 'Power / UPS', parent: 'hardware' },
    { key: 'component_failure', label: 'Component Failure', parent: 'hardware' },
    { key: 'data_breach', label: 'Data Breach', parent: 'security_incident' },
    { key: 'unauthorized_access', label: 'Unauthorized Access', parent: 'security_incident' },
    { key: 'ransomware', label: 'Ransomware', parent: 'malware' },
    { key: 'trojan', label: 'Trojan / Virus', parent: 'malware' },
    { key: 'credential_phishing', label: 'Credential Phishing', parent: 'phishing' },
    { key: 'brute_force', label: 'Brute Force', parent: 'authentication' },
    { key: 'mfa_bypass', label: 'MFA Issue', parent: 'authentication' },
    { key: 'rule_change', label: 'Rule Change', parent: 'firewall' },
    { key: 'ips_alert', label: 'IPS Alert', parent: 'firewall' },
    { key: 'critical_cve', label: 'Critical CVE', parent: 'vulnerability' },
    { key: 'scheduled_pm', label: 'Scheduled PM', parent: 'preventive_maintenance' },
    { key: 'emergency_visit', label: 'Emergency Visit', parent: 'breakdown_support' },
    { key: 'part_replacement', label: 'Part Replacement', parent: 'hardware_support' },
    { key: 'new_user', label: 'New User', parent: 'access' },
    { key: 'password_reset', label: 'Password Reset', parent: 'access' },
    { key: 'permission_change', label: 'Permission Change', parent: 'access' },
    { key: 'installation', label: 'Installation', parent: 'software' },
    { key: 'license', label: 'Licensing', parent: 'software' },
  ],
  resolution_code: [
    { key: 'fixed', label: 'Fixed', isDefault: true },
    { key: 'workaround', label: 'Workaround Provided' },
    { key: 'config_change', label: 'Configuration Change' },
    { key: 'hardware_replaced', label: 'Hardware Replaced' },
    { key: 'vendor_fixed', label: 'Resolved by Vendor' },
    { key: 'user_error', label: 'User Error / Guidance' },
    { key: 'no_fault_found', label: 'No Fault Found' },
    { key: 'cannot_reproduce', label: 'Cannot Reproduce' },
    { key: 'duplicate', label: 'Duplicate' },
    { key: 'out_of_scope_advised', label: 'Out of Scope - Customer Advised' },
    { key: 'self_recovered', label: 'Self Recovered' },
  ],
  closure_code: [
    { key: 'resolved_confirmed', label: 'Resolved - Customer Confirmed', isDefault: true },
    { key: 'resolved_auto', label: 'Resolved - Auto Closed' },
    { key: 'cancelled_by_customer', label: 'Cancelled by Customer' },
    { key: 'duplicate', label: 'Duplicate' },
    { key: 'no_response', label: 'No Customer Response' },
    { key: 'rejected', label: 'Rejected' },
  ],
  customer_type: [
    { key: 'enterprise', label: 'Enterprise' },
    { key: 'mid_market', label: 'Mid-Market', isDefault: true },
    { key: 'smb', label: 'SMB' },
    { key: 'government', label: 'Government / PSU' },
    { key: 'strategic', label: 'Strategic Account' },
  ],
  customer_status: [
    { key: 'active', label: 'Active', color: 'green', isDefault: true },
    { key: 'onboarding', label: 'Onboarding', color: 'blue' },
    { key: 'suspended', label: 'Suspended', color: 'amber' },
    { key: 'churned', label: 'Churned', color: 'gray' },
  ],
  customer_industry: [
    { key: 'manufacturing', label: 'Manufacturing' },
    { key: 'bfsi', label: 'Banking & Financial Services' },
    { key: 'healthcare', label: 'Healthcare' },
    { key: 'pharma', label: 'Pharmaceuticals' },
    { key: 'retail', label: 'Retail' },
    { key: 'it_services', label: 'IT / ITES' },
    { key: 'education', label: 'Education' },
    { key: 'government', label: 'Government' },
    { key: 'logistics', label: 'Logistics' },
    { key: 'energy', label: 'Energy & Utilities' },
    { key: 'other', label: 'Other' },
  ],
  site_type: [
    { key: 'corporate_hq', label: 'Corporate Office' },
    { key: 'plant', label: 'Plant / Factory' },
    { key: 'office', label: 'Office', isDefault: true },
    { key: 'data_center', label: 'Data Center' },
    { key: 'branch', label: 'Branch' },
    { key: 'warehouse', label: 'Warehouse' },
    { key: 'cloud', label: 'Cloud Region' },
  ],
  contract_type: [
    { key: 'amc', label: 'AMC' },
    { key: 'managed_services', label: 'Managed Services', isDefault: true },
    { key: 'noc', label: 'NOC Services' },
    { key: 'soc', label: 'SOC Services' },
    { key: 'infrastructure_support', label: 'Infrastructure Support' },
    { key: 'network_support', label: 'Network Support' },
    { key: 'security_services', label: 'Security Services' },
    { key: 'cloud_support', label: 'Cloud Support' },
    { key: 'project', label: 'Project' },
    { key: 'other', label: 'Other' },
  ],
  contract_status: [
    { key: 'draft', label: 'Draft', color: 'slate' },
    { key: 'active', label: 'Active', color: 'green' },
    { key: 'expiring', label: 'Expiring Soon', color: 'amber' },
    { key: 'expired', label: 'Expired', color: 'red' },
    { key: 'renewed', label: 'Renewed', color: 'blue' },
    { key: 'terminated', label: 'Terminated', color: 'gray' },
  ],
  entitlement_type: [
    { key: 'site_visits', label: 'Site Visits', metadata: { unit: 'visits' } },
    { key: 'pm_visits', label: 'Preventive Maintenance Visits', metadata: { unit: 'visits' } },
    { key: 'engineering_hours', label: 'Engineering Hours', metadata: { unit: 'hours' } },
    { key: 'remote_support_hours', label: 'Remote Support Hours', metadata: { unit: 'hours' } },
    { key: 'onsite_support_hours', label: 'On-site Support Hours', metadata: { unit: 'hours' } },
    { key: 'incidents', label: 'Incidents', metadata: { unit: 'incidents' } },
    { key: 'hardware_replacements', label: 'Hardware Replacements', metadata: { unit: 'count' } },
    { key: 'other', label: 'Other', metadata: { unit: 'count' } },
  ],
  scope_header: [
    { key: 'sites', label: 'Sites & Locations' },
    { key: 'device_types', label: 'Device Types' },
    { key: 'services', label: 'Services' },
    { key: 'activities', label: 'Activities' },
    { key: 'applications', label: 'Applications' },
    { key: 'users', label: 'Users & Endpoints' },
  ],
  scope_category: [
    { key: 'infrastructure', label: 'Infrastructure' },
    { key: 'network', label: 'Network' },
    { key: 'security', label: 'Security' },
    { key: 'applications', label: 'Applications' },
    { key: 'end_user', label: 'End User' },
    { key: 'cloud', label: 'Cloud' },
    { key: 'backup', label: 'Backup & DR' },
  ],
  scope_type: [
    { key: 'included', label: 'Included', isDefault: true },
    { key: 'excluded', label: 'Excluded' },
    { key: 'optional_billable', label: 'Optional (Billable)' },
  ],
  scope_status: [
    { key: 'active', label: 'Active', isDefault: true },
    { key: 'pending_review', label: 'Pending Review' },
    { key: 'retired', label: 'Retired' },
  ],
  service_category: [
    { key: 'infrastructure', label: 'Infrastructure' },
    { key: 'network', label: 'Network' },
    { key: 'security', label: 'Security' },
    { key: 'cloud', label: 'Cloud' },
    { key: 'end_user', label: 'End User Services' },
    { key: 'backup_dr', label: 'Backup & DR' },
    { key: 'maintenance', label: 'Maintenance & AMC' },
    { key: 'professional_services', label: 'Professional Services' },
  ],
  service_status: [
    { key: 'active', label: 'Active', isDefault: true, color: 'green' },
    { key: 'in_development', label: 'In Development', color: 'blue' },
    { key: 'retired', label: 'Retired', color: 'gray' },
  ],
  asset_category: [
    { key: 'server', label: 'Server' },
    { key: 'network_switch', label: 'Network Switch' },
    { key: 'router', label: 'Router' },
    { key: 'firewall', label: 'Firewall' },
    { key: 'wireless', label: 'Wireless (AP / Controller)' },
    { key: 'storage', label: 'Storage' },
    { key: 'backup_appliance', label: 'Backup Appliance' },
    { key: 'ups', label: 'UPS / Power' },
    { key: 'endpoint', label: 'Endpoint (Laptop / Desktop)' },
    { key: 'printer', label: 'Printer' },
    { key: 'security_appliance', label: 'Security Appliance' },
    { key: 'load_balancer', label: 'Load Balancer' },
    { key: 'software_license', label: 'Software License' },
    { key: 'other', label: 'Other' },
  ],
  asset_status: [
    { key: 'in_use', label: 'In Use', isDefault: true, color: 'green' },
    { key: 'in_stock', label: 'In Stock', color: 'blue' },
    { key: 'under_repair', label: 'Under Repair', color: 'amber' },
    { key: 'retired', label: 'Retired', color: 'gray' },
    { key: 'disposed', label: 'Disposed', color: 'gray' },
    { key: 'missing', label: 'Missing', color: 'red' },
  ],
  field_visit_type: [
    { key: 'breakdown', label: 'Breakdown Support' },
    { key: 'preventive_maintenance', label: 'Preventive Maintenance' },
    { key: 'installation', label: 'Installation / Deployment' },
    { key: 'inspection', label: 'Inspection' },
    { key: 'health_check', label: 'Health Check' },
    { key: 'project', label: 'Project Work' },
    { key: 'other', label: 'Other' },
  ],
  pm_frequency: [
    { key: 'weekly', label: 'Weekly' },
    { key: 'monthly', label: 'Monthly' },
    { key: 'quarterly', label: 'Quarterly', isDefault: true },
    { key: 'half_yearly', label: 'Half-Yearly' },
    { key: 'annual', label: 'Annual' },
  ],
  change_type: [
    { key: 'standard', label: 'Standard (pre-approved)' },
    { key: 'normal', label: 'Normal', isDefault: true },
    { key: 'emergency', label: 'Emergency' },
  ],
  change_risk: [
    { key: 'low', label: 'Low', level: 4, color: 'green' },
    { key: 'medium', label: 'Medium', level: 3, color: 'amber', isDefault: true },
    { key: 'high', label: 'High', level: 2, color: 'orange' },
    { key: 'very_high', label: 'Very High', level: 1, color: 'red' },
  ],
  security_severity: [
    { key: 'critical', label: 'Critical', level: 1, color: 'red' },
    { key: 'high', label: 'High', level: 2, color: 'orange' },
    { key: 'medium', label: 'Medium', level: 3, color: 'amber', isDefault: true },
    { key: 'low', label: 'Low', level: 4, color: 'blue' },
    { key: 'informational', label: 'Informational', level: 5, color: 'slate' },
  ],
  kb_type: [
    { key: 'sop', label: 'SOP' },
    { key: 'runbook', label: 'Runbook' },
    { key: 'troubleshooting', label: 'Troubleshooting Guide' },
    { key: 'faq', label: 'FAQ' },
    { key: 'known_error', label: 'Known Error' },
    { key: 'resolution', label: 'Resolution' },
    { key: 'procedure', label: 'Customer Procedure', isDefault: true },
  ],
  team_type: [
    { key: 'service_desk', label: 'Service Desk' },
    { key: 'noc', label: 'NOC' },
    { key: 'soc', label: 'SOC' },
    { key: 'field', label: 'Field Services' },
    { key: 'infrastructure', label: 'Infrastructure' },
    { key: 'network', label: 'Network' },
    { key: 'security', label: 'Security' },
    { key: 'cloud', label: 'Cloud' },
    { key: 'management', label: 'Management' },
    { key: 'general', label: 'General' },
  ],
};

export const PRIORITY_MATRIX: [string, string, string][] = [
  ['high', 'high', 'p1'],
  ['high', 'medium', 'p2'],
  ['high', 'low', 'p3'],
  ['medium', 'high', 'p2'],
  ['medium', 'medium', 'p3'],
  ['medium', 'low', 'p4'],
  ['low', 'high', 'p3'],
  ['low', 'medium', 'p4'],
  ['low', 'low', 'p4'],
];

export const TEAM_SEEDS = [
  { key: 'service_desk', name: 'Service Desk', teamType: 'service_desk', email: 'servicedesk@msp.local' },
  { key: 'noc', name: 'Network Operations Center', teamType: 'noc', email: 'noc@msp.local' },
  { key: 'soc', name: 'Security Operations Center', teamType: 'soc', email: 'soc@msp.local' },
  { key: 'field', name: 'Field Services', teamType: 'field', email: 'field@msp.local' },
  { key: 'infra', name: 'Infrastructure Team', teamType: 'infrastructure', email: 'infra@msp.local' },
  { key: 'network', name: 'Network Team', teamType: 'network', email: 'network@msp.local' },
  { key: 'cloud', name: 'Cloud Team', teamType: 'cloud', email: 'cloud@msp.local' },
];

export const CI_TYPE_SEEDS = [
  { key: 'business_service', name: 'Business Service', icon: 'briefcase', color: 'purple', attributeSchema: [{ key: 'owner', label: 'Business Owner', type: 'text' }, { key: 'tier', label: 'Service Tier', type: 'select', options: ['tier1', 'tier2', 'tier3'] }] },
  { key: 'application', name: 'Application', icon: 'app-window', color: 'violet', attributeSchema: [{ key: 'vendor', label: 'Vendor', type: 'text' }, { key: 'version', label: 'Version', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }] },
  { key: 'database', name: 'Database', icon: 'database', color: 'teal', attributeSchema: [{ key: 'engine', label: 'Engine', type: 'text' }, { key: 'version', label: 'Version', type: 'text' }, { key: 'port', label: 'Port', type: 'number' }] },
  { key: 'server', name: 'Physical Server', icon: 'server', color: 'blue', attributeSchema: [{ key: 'cpu', label: 'CPU', type: 'text' }, { key: 'memoryGb', label: 'Memory (GB)', type: 'number' }, { key: 'rack', label: 'Rack / Position', type: 'text' }, { key: 'iloIp', label: 'Management IP', type: 'text' }] },
  { key: 'virtual_machine', name: 'Virtual Machine', icon: 'box', color: 'sky', attributeSchema: [{ key: 'vcpu', label: 'vCPU', type: 'number' }, { key: 'memoryGb', label: 'Memory (GB)', type: 'number' }, { key: 'diskGb', label: 'Disk (GB)', type: 'number' }] },
  { key: 'hypervisor', name: 'Hypervisor', icon: 'layers', color: 'indigo', attributeSchema: [{ key: 'platform', label: 'Platform', type: 'select', options: ['vmware', 'hyperv', 'proxmox', 'kvm', 'nutanix'] }, { key: 'cluster', label: 'Cluster', type: 'text' }] },
  { key: 'network_switch', name: 'Network Switch', icon: 'network', color: 'green', attributeSchema: [{ key: 'ports', label: 'Port Count', type: 'number' }, { key: 'stackMember', label: 'Stack Member', type: 'text' }, { key: 'managementVlan', label: 'Management VLAN', type: 'text' }] },
  { key: 'router', name: 'Router', icon: 'route', color: 'emerald', attributeSchema: [{ key: 'wanProvider', label: 'WAN Provider', type: 'text' }, { key: 'circuitId', label: 'Circuit ID', type: 'text' }, { key: 'bandwidth', label: 'Bandwidth', type: 'text' }] },
  { key: 'firewall', name: 'Firewall', icon: 'shield', color: 'red', attributeSchema: [{ key: 'haMode', label: 'HA Mode', type: 'select', options: ['standalone', 'active_passive', 'active_active'] }, { key: 'licenseExpiry', label: 'License Expiry', type: 'date' }] },
  { key: 'wireless_controller', name: 'Wireless Controller', icon: 'radio', color: 'lime' },
  { key: 'access_point', name: 'Access Point', icon: 'wifi', color: 'lime' },
  { key: 'load_balancer', name: 'Load Balancer', icon: 'scale', color: 'cyan' },
  { key: 'storage_array', name: 'Storage Array', icon: 'hard-drive', color: 'amber', attributeSchema: [{ key: 'capacityTb', label: 'Capacity (TB)', type: 'number' }, { key: 'protocol', label: 'Protocol', type: 'text' }] },
  { key: 'nas', name: 'NAS', icon: 'hard-drive', color: 'amber' },
  { key: 'san_switch', name: 'SAN Switch', icon: 'git-branch', color: 'amber' },
  { key: 'backup_system', name: 'Backup System', icon: 'archive', color: 'orange', attributeSchema: [{ key: 'software', label: 'Backup Software', type: 'text' }, { key: 'retentionDays', label: 'Retention (days)', type: 'number' }] },
  { key: 'security_appliance', name: 'Security Appliance', icon: 'shield-check', color: 'rose' },
  { key: 'cloud_account', name: 'Cloud Account / Subscription', icon: 'cloud', color: 'sky', attributeSchema: [{ key: 'provider', label: 'Provider', type: 'select', options: ['aws', 'azure', 'gcp', 'oci', 'other'] }, { key: 'accountId', label: 'Account ID', type: 'text' }] },
  { key: 'cloud_resource', name: 'Cloud Resource', icon: 'cloud-cog', color: 'sky', attributeSchema: [{ key: 'resourceType', label: 'Resource Type', type: 'text' }, { key: 'region', label: 'Region', type: 'text' }] },
  { key: 'ups', name: 'UPS', icon: 'battery-charging', color: 'yellow', attributeSchema: [{ key: 'capacityKva', label: 'Capacity (kVA)', type: 'number' }, { key: 'batteryReplacedOn', label: 'Battery Replaced On', type: 'date' }] },
  { key: 'endpoint', name: 'Endpoint', icon: 'laptop', color: 'slate' },
  { key: 'printer', name: 'Printer', icon: 'printer', color: 'slate' },
  { key: 'ip_phone', name: 'IP Phone / Voice', icon: 'phone', color: 'slate' },
  { key: 'iot_device', name: 'IoT / OT Device', icon: 'cpu', color: 'slate' },
  { key: 'other', name: 'Other', icon: 'box', color: 'gray' },
];

export const RELATIONSHIP_TYPE_SEEDS = [
  { key: 'depends_on', name: 'Depends on', inverseName: 'Is dependency of' },
  { key: 'runs_on', name: 'Runs on', inverseName: 'Runs' },
  { key: 'hosted_on', name: 'Hosted on', inverseName: 'Hosts' },
  { key: 'connected_to', name: 'Connected to', inverseName: 'Connected to' },
  { key: 'supports', name: 'Supports', inverseName: 'Supported by' },
  { key: 'protected_by', name: 'Protected by', inverseName: 'Protects' },
  { key: 'backed_up_by', name: 'Backed up by', inverseName: 'Backs up' },
  { key: 'located_at', name: 'Located at', inverseName: 'Location of' },
  { key: 'uses', name: 'Uses', inverseName: 'Used by' },
  { key: 'member_of', name: 'Member of', inverseName: 'Contains' },
  { key: 'manages', name: 'Manages', inverseName: 'Managed by' },
  { key: 'monitored_by', name: 'Monitored by', inverseName: 'Monitors' },
];

export const KB_CATEGORY_SEEDS = [
  { key: 'noc_procedures', name: 'NOC Procedures', domain: 'noc' as const },
  { key: 'soc_procedures', name: 'SOC Procedures', domain: 'soc' as const },
  { key: 'amc_procedures', name: 'AMC & Field Procedures', domain: 'amc' as const },
  { key: 'runbooks', name: 'Runbooks', domain: 'general' as const },
  { key: 'troubleshooting', name: 'Troubleshooting Guides', domain: 'general' as const },
  { key: 'known_errors', name: 'Known Errors', domain: 'general' as const },
  { key: 'customer_procedures', name: 'Customer-Specific Procedures', domain: 'general' as const },
  { key: 'faq', name: 'FAQs', domain: 'general' as const },
];
