import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { inflateSync } from 'node:zlib';

/**
 * The brand assets the web application ships: the mark (mark.svg) is the favicon and the source of the raster
 * icon set generated by apps/web/scripts/make-icons.mjs; index.html and site.webmanifest point at them. No
 * database, no image library: PNG and ICO headers are read by hand.
 */
const web = resolve(__dirname, '../../web');
const pub = join(web, 'public');
const html = readFileSync(join(web, 'index.html'), 'utf8');

/** Width, height, colour type and the alpha of pixel (0,0) of a PNG, without any image library. */
function png(file: string) {
  const b = readFileSync(file);
  expect(b.readUInt32BE(0), `${file} is a PNG`).toBe(0x89504e47);
  const w = b.readUInt32BE(16), h = b.readUInt32BE(20), ct = b[25]!;
  expect(b[24], `${file} is 8-bit`).toBe(8); // the first-pixel read below assumes one byte per sample
  const idat: Buffer[] = [];
  for (let p = 8; p < b.length; ) { const len = b.readUInt32BE(p); if (b.toString('ascii', p + 4, p + 8) === 'IDAT') idat.push(b.subarray(p + 8, p + 8 + len)); p += 12 + len; }
  const raw = inflateSync(Buffer.concat(idat));
  const bpp = ct === 6 ? 4 : ct === 2 ? 3 : ct === 4 ? 2 : 1;
  const first = raw.subarray(1, 1 + bpp); // byte 0 of a scanline is the filter type; the first pixel is raw under every filter
  return { w, h, ct, firstAlpha: ct === 6 ? first[3]! : ct === 4 ? first[1]! : 255 };
}
/** The entries of an ICO container: size and whether the data is a PNG. */
function ico(file: string) {
  const b = readFileSync(file);
  expect(b.readUInt16LE(2)).toBe(1);
  return Array.from({ length: b.readUInt16LE(4) }, (_, i) => { const e = 6 + 16 * i; const off = b.readUInt32LE(e + 12); return { size: b[e]!, png: b.readUInt32BE(off) === 0x89504e47 }; });
}
const walk = (dir: string): string[] => readdirSync(dir).flatMap((n) => { const p = join(dir, n); return statSync(p).isDirectory() ? walk(p) : /\.tsx?$/.test(n) ? [p] : []; });

const ICON_LINKS = ['/favicon.ico', '/favicon.svg', '/favicon-32.png', '/favicon-16.png', '/apple-touch-icon.png', '/site.webmanifest'];

describe('brand assets', () => {
  it('index.html declares the icon set and every href exists', () => {
    const links = Array.from(html.matchAll(/<link\s+rel="(icon|apple-touch-icon|manifest)"\s+href="([^"]+)"[^>]*>/g));
    const hrefs = links.map((m) => m[2]!);
    expect([...hrefs].sort()).toEqual([...ICON_LINKS].sort());
    for (const href of hrefs) expect(existsSync(join(pub, href)), `${href} exists in public/`).toBe(true);
    const svg = links.find((m) => m[2] === '/favicon.svg')!;
    expect(svg[0]).toContain('type="image/svg+xml"');
    expect(links.filter((m) => m[1] === 'manifest')).toHaveLength(1);
    expect(html).toContain('<title>Progression</title>');
    expect(html).toContain('<meta name="theme-color" content="#ffffff" />');
    expect(html).toContain('<meta name="application-name" content="Progression" />');
  });

  it('the mark and the favicon are the same vector', () => {
    const mark = readFileSync(join(pub, 'mark.svg'), 'utf8');
    expect(mark).toBe(readFileSync(join(pub, 'favicon.svg'), 'utf8'));
    expect(mark).toContain('viewBox="0 0 32 32"');
    expect(mark.match(/<path\b/g)).toHaveLength(3);
    const colours = new Set((mark.match(/#[0-9a-fA-F]{6}\b/g) ?? []).map((c) => c.toLowerCase()));
    expect([...colours]).toEqual(['#ee3137']);
    expect(mark).not.toContain('<script');
    expect(mark).not.toContain('href="http');
    expect(mark.length).toBeLessThan(8192);
  });

  it('PNG icons have the declared size and transparency', () => {
    const table: [string, number][] = [['favicon-16.png', 16], ['favicon-32.png', 32], ['icon-192.png', 192], ['icon-512.png', 512]];
    for (const [name, size] of table) {
      const p = png(join(pub, name));
      expect([p.w, p.h], `${name} is ${size} square`).toEqual([size, size]);
      expect(p.ct, `${name} is RGBA`).toBe(6);
      expect(p.firstAlpha, `${name} corner is transparent`).toBe(0);
    }
    const touch = png(join(pub, 'apple-touch-icon.png'));
    expect([touch.w, touch.h]).toEqual([180, 180]);
    expect(touch.ct === 2 || touch.firstAlpha === 255, 'the touch icon is opaque for iOS').toBe(true);
  });

  it('favicon.ico holds the 16 and 32 pixel entries as PNG', () => {
    expect(ico(join(pub, 'favicon.ico'))).toEqual([{ size: 16, png: true }, { size: 32, png: true }]);
  });

  it('site.webmanifest names Progression and its icons exist at the declared sizes', () => {
    const manifest = JSON.parse(readFileSync(join(pub, 'site.webmanifest'), 'utf8')) as { name: string; short_name: string; theme_color: string; background_color: string; icons: { src: string; sizes: string }[] };
    expect(manifest.name).toBe('Progression');
    expect(manifest.short_name).toBe('Progression');
    expect(manifest.theme_color).toBe('#ffffff');
    expect(manifest.background_color).toBe('#fafafa');
    expect(manifest.icons.length).toBeGreaterThanOrEqual(2);
    for (const icon of manifest.icons) {
      expect(existsSync(join(pub, icon.src)), `${icon.src} exists`).toBe(true);
      const size = Number(icon.sizes.split('x')[0]);
      const p = png(join(pub, icon.src));
      expect([p.w, p.h], `${icon.src} is ${icon.sizes}`).toEqual([size, size]);
    }
  });

  it('every static asset referenced from the web source exists in public/', () => {
    const refs = new Set<string>();
    for (const file of walk(join(web, 'src'))) {
      const text = readFileSync(file, 'utf8');
      for (const m of text.matchAll(/src="\/([\w.-]+)"/g)) refs.add(m[1]!);
      for (const m of text.matchAll(/src: '\/([\w.-]+)'/g)) refs.add(m[1]!);
    }
    expect(refs.has('logo.png')).toBe(true);
    expect(refs.has('mark.svg')).toBe(true);
    for (const ref of refs) expect(existsSync(join(pub, ref)), `/${ref} exists in public/`).toBe(true);
    const shell = readFileSync(join(web, 'src/layouts/AppShell.tsx'), 'utf8');
    expect(shell).toContain('src="/mark.svg"');
    expect(shell).not.toContain('src="/favicon.svg"');
  });
});
